FROM oven/bun:1 AS build

WORKDIR /app

COPY ./apps/server/ ./

ENV NODE_ENV=production

RUN bun install --frozen-lockfile

RUN bun build --compile --minify-whitespace --minify-syntax --target bun --outfile server ./src/index.ts

FROM gcr.io/distroless/base

WORKDIR /app

COPY --from=build /app/src/db/migrations src/db/migrations
COPY --from=build /app/posts.json posts.json
COPY --from=build /app/server server

CMD ["./server"]

EXPOSE 3000